---

is_debug: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 10005
mongodb:
  host: ns-us-mongodb
  port: 27017
  username: nsuser
  password: nsuser
  auth_db: notes-system
  database: notes-system
  collection: users